// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file NestedElement.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _NestedElement_H_
#define _NestedElement_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(NestedElement_SOURCE)
#define NestedElement_DllAPI __declspec( dllexport )
#else
#define NestedElement_DllAPI __declspec( dllimport )
#endif // NestedElement_SOURCE
#else
#define NestedElement_DllAPI
#endif
#else
#define NestedElement_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

namespace nested
{
    /*!
     * @brief This class represents the structure NestedElement defined by the user in the IDL file.
     * @ingroup NESTEDELEMENT
     */
    class NestedElement
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport NestedElement();
        
        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~NestedElement();
        
        /*!
         * @brief Copy constructor.
         * @param x Reference to the object nested::NestedElement that will be copied.
         */
        eProsima_user_DllExport NestedElement(const NestedElement &x);
        
        /*!
         * @brief Move constructor.
         * @param x Reference to the object nested::NestedElement that will be copied.
         */
        eProsima_user_DllExport NestedElement(NestedElement &&x);
        
        /*!
         * @brief Copy assignment.
         * @param x Reference to the object nested::NestedElement that will be copied.
         */
        eProsima_user_DllExport NestedElement& operator=(const NestedElement &x);
        
        /*!
         * @brief Move assignment.
         * @param x Reference to the object nested::NestedElement that will be copied.
         */
        eProsima_user_DllExport NestedElement& operator=(NestedElement &&x);
        
        /*!
         * @brief This function copies the value in member stringTest
         * @param _stringTest New value to be copied in member stringTest
         */
        inline eProsima_user_DllExport void stringTest(const std::string &_stringTest)
        {
            m_stringTest = _stringTest;
        }

        /*!
         * @brief This function moves the value in member stringTest
         * @param _stringTest New value to be moved in member stringTest
         */
        inline eProsima_user_DllExport void stringTest(std::string &&_stringTest)
        {
            m_stringTest = std::move(_stringTest);
        }

        /*!
         * @brief This function returns a constant reference to member stringTest
         * @return Constant reference to member stringTest
         */
        inline eProsima_user_DllExport const std::string& stringTest() const
        {
            return m_stringTest;
        }

        /*!
         * @brief This function returns a reference to member stringTest
         * @return Reference to member stringTest
         */
        inline eProsima_user_DllExport std::string& stringTest()
        {
            return m_stringTest;
        }
        /*!
         * @brief This function sets a value in member longTest
         * @param _longTest New value for member longTest
         */
        inline eProsima_user_DllExport void longTest(int32_t _longTest)
        {
            m_longTest = _longTest;
        }

        /*!
         * @brief This function returns the value of member longTest
         * @return Value of member longTest
         */
        inline eProsima_user_DllExport int32_t longTest() const
        {
            return m_longTest;
        }

        /*!
         * @brief This function returns a reference to member longTest
         * @return Reference to member longTest
         */
        inline eProsima_user_DllExport int32_t& longTest()
        {
            return m_longTest;
        }
        
        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(const nested::NestedElement& data, size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;
        
    private:
        std::string m_stringTest;
        int32_t m_longTest;
    };
}

#endif // _NestedElement_H_