// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file NestedElement.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "NestedElement.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

nested::NestedElement::NestedElement()
{

    m_longTest = 0;
}

nested::NestedElement::~NestedElement()
{
}

nested::NestedElement::NestedElement(const NestedElement &x)
{
    m_stringTest = x.m_stringTest;
    m_longTest = x.m_longTest;
}

nested::NestedElement::NestedElement(NestedElement &&x)
{
    m_stringTest = std::move(x.m_stringTest);
    m_longTest = x.m_longTest;
}

nested::NestedElement& nested::NestedElement::operator=(const NestedElement &x)
{
    m_stringTest = x.m_stringTest;
    m_longTest = x.m_longTest;
    
    return *this;
}

nested::NestedElement& nested::NestedElement::operator=(NestedElement &&x)
{
    m_stringTest = std::move(x.m_stringTest);
    m_longTest = x.m_longTest;
    
    return *this;
}

size_t nested::NestedElement::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t nested::NestedElement::getCdrSerializedSize(const nested::NestedElement& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.stringTest().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void nested::NestedElement::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_stringTest;
    scdr << m_longTest;
}

void nested::NestedElement::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_stringTest;
    dcdr >> m_longTest;
}

size_t nested::NestedElement::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            



    return current_align;
}

bool nested::NestedElement::isKeyDefined()
{
    return false;
}

void nested::NestedElement::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
	 
}
