package us.ihmc.idl;

/**
 * Useful functions to work with the datatypes generated by IDL
 * 
 * These functions are called from the generated class files.
 * 
 * @author Jesper Smith
 *
 */
public class IDLTools
{
   /**
    * Compare two StringBuilder classes char by char
    * 
    * @param a First StringBuilder
    * @param b Second StringBuilder
    * @return true if length and all characters are equal
    */
   public static boolean equals(StringBuilder a, StringBuilder b)
   {
      if(a.length() == b.length())
      {
         for(int i = 0; i < a.length(); i++)
         {
            if(a.charAt(i) != b.charAt(i))
            {
               return false;
            }
         }
      }
      else
      {
         return false;
      }
      
      return true;
   }
   
}
