/**
 * Copyright 2017 Florida Institute for Human and Machine Cognition (IHMC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package us.ihmc.idl;

/**
 * Useful functions to work with the datatypes generated by IDL
 * 
 * These functions are called from the generated class files.
 * 
 * @author Jesper Smith
 *
 */
public class IDLTools
{
   /**
    * Compare two StringBuilder classes char by char
    * 
    * @param a First StringBuilder
    * @param b Second StringBuilder
    * @return true if length and all characters are equal
    */
   public static boolean equals(StringBuilder a, StringBuilder b)
   {
      if(a.length() == b.length())
      {
         for(int i = 0; i < a.length(); i++)
         {
            if(a.charAt(i) != b.charAt(i))
            {
               return false;
            }
         }
      }
      else
      {
         return false;
      }
      
      return true;
   }
   
}
