name: Run Gradle test (Linux, self-hosted)

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'recursive'
      - name: LFS checkout
        run: |
          git lfs install --local
          git lfs fetch
          git lfs pull
          git lfs ls-files -l
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5
      - name: Run tests
        run: |
          gradle compositeTask -PtaskName=compileJava || true
          gradle compositeTask -PtaskName=compileJava
          gradle compositeTask -PtaskName=test --info --stacktrace --no-daemon -PrunningOnCIServer=true
      - name: Publish Test Report - ${{ inputs.test-category }}
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
