name: Run Gradle test (all platforms)

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'recursive'
      - name: LFS checkout
        run: |
          git lfs install --local
          git lfs fetch
          git lfs pull
          git lfs ls-files -l
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5
      - name: Run tests
        run: |
          patch ihmc-pub-sub/thirdparty/Fast-RTPS/resources/xsd/fastRTPS_profiles.xsd ihmc-pub-sub/patches/fastRTPS_profiles.patch
          gradle compositeTask --stacktrace --info -PtaskName=test
  test-windows:
    runs-on: [windows-2019]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'recursive'
      - name: LFS checkout
        run: |
          git lfs install --local
          git lfs fetch
          git lfs pull
          git lfs ls-files -l
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5
      - name: Run tests
        run: |
          patch ihmc-pub-sub/thirdparty/Fast-RTPS/resources/xsd/fastRTPS_profiles.xsd ihmc-pub-sub/patches/fastRTPS_profiles.patch
          gradle compositeTask --stacktrace --info -PtaskName=test
  test-macos-intel:
    runs-on: [macos-12] # macos-12 is exclusively x86_64 intel
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'recursive'
      - name: LFS checkout
        run: |
          git lfs install --local
          git lfs fetch
          git lfs pull
          git lfs ls-files -l
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5
      - name: Run tests
        run: |
          patch ihmc-pub-sub/thirdparty/Fast-RTPS/resources/xsd/fastRTPS_profiles.xsd ihmc-pub-sub/patches/fastRTPS_profiles.patch
          gradle compositeTask --stacktrace --info -PtaskName=test
  test-macos-arm:
    runs-on: [macos-14] # macos-14 runner is exclusively arm64
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'recursive'
      - name: LFS checkout
        run: |
          git lfs install --local
          git lfs fetch
          git lfs pull
          git lfs ls-files -l
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5
      - name: Run tests
        run: |
          patch ihmc-pub-sub/thirdparty/Fast-RTPS/resources/xsd/fastRTPS_profiles.xsd ihmc-pub-sub/patches/fastRTPS_profiles.patch
          gradle compositeTask --stacktrace --info -PtaskName=test
